# Generated by Django 4.2.11 on 2024-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_AuthUsers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='picture_admin',
            field=models.ImageField(default='no_image', upload_to='profile/admin_pic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='picture_cli',
            field=models.ImageField(default='no_image', upload_to='profile/client_pic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='picture_emp',
            field=models.ImageField(default='no_image', upload_to='profile/employee_pic/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerente',
            name='picture_admin',
            field=models.ImageField(default='no_image', upload_to='profile/manager_pic/'),
            preserve_default=False,
        ),
    ]
