# Generated by Django 4.2.11 on 2024-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_AuthUsers', '0003_administrador_picture_admin_cliente_picture_cli_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='farm_emp',
            new_name='farmacia_id',
        ),
        migrations.RenameField(
            model_name='gerente',
            old_name='gerente_farm',
            new_name='farmacia_id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='picture_admin',
            field=models.ImageField(blank=True, null=True, upload_to='profile/admin_pic/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='picture_cli',
            field=models.ImageField(blank=True, null=True, upload_to='profile/client_pic/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='picture_emp',
            field=models.ImageField(blank=True, null=True, upload_to='profile/employee_pic/'),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='picture_admin',
            field=models.ImageField(blank=True, null=True, upload_to='profile/manager_pic/'),
        ),
    ]
