# Generated by Django 4.2.11 on 2024-05-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_ProductProvider', '0001_initial'),
        ('App_AuthUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=100)),
                ('descripcion_promo', models.TextField()),
                ('descuento_promo', models.IntegerField(default=0)),
                ('fecha_fin_promo', models.DateField(blank=True, null=True)),
                ('cliente_id', models.ManyToManyField(blank=True, to='App_AuthUsers.cliente')),
                ('producto_id', models.ManyToManyField(to='App_ProductProvider.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_CartPromos.carritocompra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='producto_carrito',
            field=models.ManyToManyField(through='App_CartPromos.ContenidoCarrito', to='App_ProductProvider.producto'),
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente'),
        ),
    ]
