# Generated by Django 4.2.11 on 2024-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CartPromos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompra',
            name='codigo_compra',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenidocarrito',
            name='cantidad_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
