# Generated by Django 4.2.11 on 2024-05-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_CartPromos', '0002_carritocompra_codigo_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
