# Generated by Django 4.2.11 on 2024-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_CartPromos', '0003_alter_carritocompra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidocarrito',
            name='cantidad_producto',
            field=models.IntegerField(default=1),
        ),
    ]
