# Generated by Django 4.2.11 on 2024-05-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_farm', models.CharField(max_length=8)),
                ('nombre_farm', models.CharField(max_length=200)),
                ('direccion_farm', models.CharField(max_length=200)),
                ('telefono_farm', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_prod', models.IntegerField()),
                ('imagen_prod', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('nombre_prod', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('cif_farm', models.CharField(max_length=8)),
                ('categoria_id', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.categoria')),
                ('farmacia_id', models.ForeignKey(db_column='farmacia_id', on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_prov', models.CharField(max_length=8)),
                ('nombre_prov', models.CharField(max_length=200)),
                ('direccion_prov', models.CharField(max_length=200)),
                ('telefono_prov', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuministroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('costo_ud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cn_prod', models.IntegerField()),
                ('cif_prov', models.CharField(max_length=8)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.producto')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField()),
                ('composicion', models.TextField()),
                ('modo_de_uso', models.TextField()),
                ('fecha_vencimiento', models.DateField()),
                ('cn_prod', models.CharField(max_length=10)),
                ('producto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_id',
            field=models.ManyToManyField(through='App_ProductProvider.SuministroProducto', to='App_ProductProvider.proveedor'),
        ),
    ]
