# Generated by Django 4.2.11 on 2024-05-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ProductProvider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suministroproducto',
            old_name='fecha',
            new_name='fecha_pedido',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_prod',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
