# Generated by Django 4.2.11 on 2024-06-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ProductProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
