# Generated by Django 4.2.11 on 2024-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ProductProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cif_farm',
            field=models.CharField(default='PH001234', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suministroproducto',
            name='cn_prod',
            field=models.IntegerField(),
        ),
    ]
