# Generated by Django 4.2.11 on 2024-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ProductProvider', '0002_producto_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
