# Generated by Django 4.2.11 on 2024-06-03 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_AuthUsers', '0001_initial'),
        ('App_CartPromos', '0001_initial'),
        ('App_ProductProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('direccion_envio', models.CharField(max_length=200)),
                ('codigo_postal', models.IntegerField()),
                ('municipio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('total_pago', models.FloatField()),
                ('carrito_id', models.OneToOneField(db_column='carrito_id', on_delete=django.db.models.deletion.CASCADE, to='App_CartPromos.carritocompra')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha_votacion', models.DateField(default=django.utils.timezone.now)),
                ('comenta_votacion', models.TextField()),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_al_dia', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='App_ProductProvider.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_sub', models.CharField(max_length=200)),
                ('descripcion_sub', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente_id', models.OneToOneField(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=30)),
                ('titular_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('id_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_email_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateField()),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
                ('compra_id', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, to='App_SellsSubs.compra')),
                ('subscripcion_id', models.ForeignKey(db_column='subscripcion_id', on_delete=django.db.models.deletion.CASCADE, to='App_SellsSubs.subscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.OneToOneField(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='App_AuthUsers.cliente')),
                ('compra_id', models.ManyToManyField(to='App_SellsSubs.compra')),
                ('pago_id', models.ForeignKey(db_column='pago_id', on_delete=django.db.models.deletion.CASCADE, to='App_SellsSubs.pago')),
            ],
        ),
    ]
