# Generated by Django 4.2.11 on 2024-05-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='empleado_id',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
