# Generated by Django 4.2.11 on 2024-06-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='subscripcion_id',
            field=models.ForeignKey(blank=True, db_column='subscripcion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='App_SellsSubs.subscripcion'),
        ),
    ]
