# Generated by Django 4.2.11 on 2024-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0002_alter_pago_subscripcion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
