# Generated by Django 4.2.11 on 2024-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0002_remove_compra_empleado_id_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_tarjeta',
            field=models.CharField(default='Caixa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='titular_tarjeta',
            field=models.CharField(default='Elvis', max_length=100),
            preserve_default=False,
        ),
    ]
