# Generated by Django 4.2.11 on 2024-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0003_pago_tipo_tarjeta_pago_titular_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='direccion_envio',
            field=models.CharField(default='pepe', max_length=200),
            preserve_default=False,
        ),
    ]
