# Generated by Django 4.2.11 on 2024-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0003_alter_votacion_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='titulo',
            field=models.CharField(default='hola', max_length=250),
            preserve_default=False,
        ),
    ]
