# Generated by Django 4.2.11 on 2024-05-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0004_pago_direccion_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='direccion_envio',
        ),
        migrations.AddField(
            model_name='compra',
            name='ciudad',
            field=models.CharField(default='sevilla', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='codigo_postal',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_envio',
            field=models.CharField(default='calle', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='pais',
            field=models.CharField(default='españa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='provincia',
            field=models.CharField(default='sevilla', max_length=100),
            preserve_default=False,
        ),
    ]
