# Generated by Django 4.2.11 on 2024-05-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0005_remove_pago_direccion_envio_compra_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='pais',
        ),
    ]
