# Generated by Django 4.2.11 on 2024-05-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SellsSubs', '0006_remove_compra_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='ciudad',
            new_name='municipio',
        ),
    ]
